### ISSUE TITLE
BibRecord: lxml Python 2.4 compatibility

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1418]
Originally on 2013-03-21

It looks like there is an issue of compatibility version between Invenio's lxml usage and Python 2.4.

```
BibMatch: Parsing input file ...Traceback (most recent call last):
  File "/opt/invenio/bin/bibmatch", line 87, in ? 
    main()
  File "/usr/lib/python2.4/site-packages/invenio/bibmatch_engine.py", line 1217, in main
    records = create_records(file_read)
  File "/usr/lib/python2.4/site-packages/invenio/bibrecord.py", line 117, in create_records
    parser=parser, keep_singletons=keep_singletons) for record_xml in record_xmls]
  File "/usr/lib/python2.4/site-packages/invenio/bibrecord.py", line 172, in create_record
    keep_singletons=keep_singletons)
  File "/usr/lib/python2.4/site-packages/invenio/bibrecord.py", line 1316, in _create_record_lxml
    controlfield_iterator = tree.iter(tag='controlfield')
AttributeError: 'etree._ElementTree' object has no attribute 'iter'
```

Possibly introduced in 0aae780bbdc7588e2a27c6e180403a8bd10fc15e.

**Comment by aw-bib** [comment]
@tiborsimko, @kaplun It seems that we see this problem on maint-1.1 in join2-repos as well in a completely unrelated area. The code in question takes an `xmlstr` containing a valid collection/record-tree from an external MarcXML-source. As we do not need all tags I want to extract them easily so I throw these records at `bibrecord`:

    rec = create_records(xmlstr.encode('utf-8'))

This fails on both our FreeBSD 9.1-RELEASE-p1 box as well as on one of our Debians running debian 6.0.10 (oldstable, aka 'squeeze'). Both boxes would use `lxml` as parser with the above mentioned statement. If I do

    rec = create_records(xmlstr.encode('utf-8'), parser='minidom')

everything is fine. So it seems to be the lxml-parser. However, both boxes run `python 2.7` with `py27-lxml-3.3.5` and `pyhton 2.6` with `python-lxml 2.2.8-2+deb6u1` respectively. So it seems to persist even in newer versions.

I wonder what else breaks if `create_records()` dies and if we should not enforce `minidom` therefore until it is fixed.

**Comment by tiborsimko** [comment]
@aw-bib Do you have a small MARCXML snippet sample on which we could test PR #2148 or PR #2275?

**Comment by tiborsimko** [comment]
> py27-lxml-3.3.5 and pyhton 2.6 with python-lxml 2.2.8-2+deb6u1 respectively. 

@aw-bib Alternatively to sending snippet, please note that our `requirements.txt` file instructs to use `lxml==3.1.2`.  Since your Python version is not 2.4 anymore, can you please try `sudo pip install lxml==3.1.2 --upgrade ` and see if your problems persist?

(Note that we discussed lxml requirements in https://github.com/inveniosoftware/invenio/pull/2148#discussion_r16703261)

**Comment by aw-bib** [comment]
@tiborsimko WRT to `pip`: I fear this is not an option on our servers. We (our computing centres) use only distribution maintained packages from stable server releases so we can know what each partner has running.

WRT to the MarcXML: of course :) I Didn't alter anything from the dump below, it's the XML string I feed into create_records(). This is just the plain dump down form Marc21 exposed by GVK. @jmartinm may remember this kind of data as I gave him the interface for inspire/cds book imports (a long standing wish of Jens.)

    <?xml version="1.0" encoding="UTF-8"?><collection><record xmlns="http://www.loc.gov/MARC21/slim">
      <leader>xxxxxnam a22yyyyy c 4500</leader>
      <controlfield tag="001">665699638</controlfield>
      <controlfield tag="003">DE-601</controlfield>
      <controlfield tag="005">20130414023358.0</controlfield>
      <controlfield tag="008">110810s2011    gw            000 0 eng d</controlfield>
      <datafield ind1=" " ind2=" " tag="015">
        <subfield code="a">11N32</subfield>
        <subfield code="2">dnb</subfield>
      </datafield>
      <datafield ind1="7" ind2=" " tag="016">
        <subfield code="a">1014071542</subfield>
        <subfield code="2">DE-101</subfield>
      </datafield>
      <datafield ind1=" " ind2=" " tag="020">
        <subfield code="a">9783893367146 (Pb.)</subfield>
        <subfield code="c">EUR 28.00 (DE)</subfield>
        <subfield code="9">978-3-89336-714-6</subfield>
      </datafield>
      <datafield ind1=" " ind2=" " tag="035">
        <subfield code="a">(OCoLC)838495572</subfield>
      </datafield>
      <datafield ind1=" " ind2=" " tag="035">
        <subfield code="a">(DE-101)1014071542</subfield>
      </datafield>
      <datafield ind1=" " ind2=" " tag="035">
        <subfield code="a">(DE-599)DNB1014071542</subfield>
      </datafield>
      <datafield ind1=" " ind2=" " tag="040">
        <subfield code="a">GBVCP</subfield>
        <subfield code="b">ger</subfield>
        <subfield code="c">GBVCP</subfield>
        <subfield code="e">rakwb</subfield>
      </datafield>
      <datafield ind1="0" ind2=" " tag="041">
        <subfield code="a">eng</subfield>
      </datafield>
      <datafield ind1="0" ind2="0" tag="082">
        <subfield code="a">530</subfield>
      </datafield>
      <datafield ind1="0" ind2="9" tag="082">
        <subfield code="a">530</subfield>
      </datafield>
      <datafield ind1=" " ind2=" " tag="084">
        <subfield code="a">31.76</subfield>
        <subfield code="9">Numerische Mathematik</subfield>
        <subfield code="2">bcl</subfield>
      </datafield>
      <datafield ind1="0" ind2="0" tag="245">
        <subfield code="a">Fast methods for long-range interactions in complex systems</subfield>
        <subfield code="b">Summer School, 6 - 10 September 2010, Forschungszentrum Jülich GmbH ; lecture notes</subfield>
        <subfield code="c">ed. by Godehard Sutmann ...</subfield>
      </datafield>
      <datafield ind1="3" ind2=" " tag="260">
        <subfield code="a">Jülich</subfield>
        <subfield code="b">Forschungszentrum Jülich</subfield>
        <subfield code="c">2011</subfield>
      </datafield>
      <datafield ind1=" " ind2=" " tag="300">
        <subfield code="a">2, II, 167 S.</subfield>
        <subfield code="c">240 mm x 170 mm</subfield>
      </datafield>
      <datafield ind1="0" ind2=" " tag="490">
        <subfield code="a">Schriften des Forschungszentrums Jülich</subfield>
        <subfield code="a">IAS Series</subfield>
        <subfield code="v">6</subfield>
      </datafield>
      <datafield ind1=" " ind2="0" tag="653">
        <subfield code="a">Paperback / softback</subfield>
      </datafield>
      <datafield ind1="1" ind2=" " tag="700">
        <subfield code="a">Sutmann, Godehard</subfield>
      </datafield>
      <datafield ind1="2" ind2=" " tag="710">
        <subfield code="a">Institute for Advanced Simulation</subfield>
        <subfield code="0">(DE-601)600045838</subfield>
        <subfield code="0">(DE-588)16008837-9</subfield>
      </datafield>
      <datafield ind1="2" ind2=" " tag="711">
        <subfield code="a">Summer School</subfield>
        <subfield code="d">(2010.09.06-10</subfield>
        <subfield code="c">Jülich)</subfield>
      </datafield>
      <datafield ind1=" " ind2=" " tag="830">
        <subfield code="w">(DE-601)61363229X</subfield>
        <subfield code="w">(DE-600)25251004</subfield>
        <subfield code="a">Schriften des Forschungszentrums Jülich / IAS series</subfield>
        <subfield code="p">Schriften des Forschungszentrums Jülich</subfield>
        <subfield code="p">Forschungszentrum Jülich</subfield>
        <subfield code="v">6</subfield>
        <subfield code="9">600</subfield>
      </datafield>
      <datafield ind1="4" ind2="2" tag="856">
        <subfield code="y">Inhaltsverzeichnis</subfield>
        <subfield code="u">http://www.gbv.de/dms/tib-ub-hannover/665699638.pdf</subfield>
        <subfield code="m">V:DE-601;DE-89</subfield>
        <subfield code="3">Inhaltsverzeichnis</subfield>
      </datafield>
      <datafield ind1=" " ind2=" " tag="900">
        <subfield code="a">GBV</subfield>
        <subfield code="b">TIB/UB Hannover &lt;89&gt;</subfield>
        <subfield code="d">RS 9035(6)</subfield>
        <subfield code="x">L</subfield>
        <subfield code="z">C</subfield>
      </datafield>
      <datafield ind1=" " ind2=" " tag="954">
        <subfield code="a">70</subfield>
        <subfield code="b">1264444893</subfield>
        <subfield code="c">01</subfield>
        <subfield code="d">RS 9035(6)</subfield>
        <subfield code="e">f</subfield>
        <subfield code="x">0089</subfield>
      </datafield>
    </record></collection>

**Comment by tiborsimko** [comment]
>  WRT to pip: I fear this is not an option on our servers. We (our computing centres) use only distribution maintained packages from stable server releases so we can know what each partner has running.

With pip you can also know which versions are running at each partner site (`pip freeze`).  This is OS independent, so may be even better?

If you cannot find necessary pre-packaged versions of python-lxml for this or that platform, you can perhaps create the package yourself, as we have been doing here for older SLC4/SLC5 boxes:

- http://invenio-software.org/wiki/Installation/InvenioOnSLC5#A.3BuildPythonicRPMs

An alternative would be to debug troubles on all the various lxml versions you are using, and submit us a patch that would work on all of them.  This would be kind of laborious and not scalable.  Just compiling package versions that are recommended seems easier.

Your computing teams must see this also with other apps running on the servers, isn't it?

(BTW, Invenio 2 itself will be hosted on pypi, so...)

> WRT to the MarcXML: of course :)

Thanks; this one works well for me, but I'm using the recommened lxml version.

**Comment by tiborsimko** [comment]
> rec = create_records(xmlstr.encode('utf-8'))

BTW, just to make triple sure, `create_record` functions expect regular Python binary strings as input, not Python unicode strings. Hence, if your `type(xmlstr)` is already `str`, you should remove `encode` part and pass it directly.  If your `type(xmlstr)` is `unicode`, then the above `encode` call is good.   Just trying to make sure the problems are not caused due to this.

**Comment by aw-bib** [comment]
Good point. Checked: `type(xmlstr)` returns `unicode`, seems the `encode()` is correct.

    $ ./gvkfetch.py ppn=021394202
    <type 'unicode'>

**Comment by jirikuncar** [comment]
Is anybody still using Python 2.4 for production?

**Comment by tiborsimko** [comment]
> Is anybody still using Python 2.4 for production?

Some installations using invenio/maint-1.1 still might.  (And starting from soon-to-be-released v1.2.0 we require Python-2.6 anyway.)

WRT lxml and maint-1.1 also, see PR #2275 and PR #2148 that is in WIP.  CC-ing @kasioumis

**Comment by aw-bib** [comment]
@jirikuncar if you're on RedHat Enterprise 5.x (and derivatives), which has regular support till 2017 and extended support till 2020(!) you're most likely on 2.4.

So, _especially_ on production where you have server Linuxes you'll have older versions.

But note that at least the the issue I mentioned came about on a quite fresh FreeBSD 9 in python 2.7.8 and was also seen on a debian oldstable supported till 2016 and running afaik python 2.6.

**Comment by jirikuncar** [comment]
Patches are welcome although I'm afraid that we can no longer support archaic versions of Python <2.7. Please look forward to bright Python 3 future.
